# Introduction to numpy 


In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6])

In [3]:
print(array1)
print(type(array1))
print(array1.shape)
b = np.array([[1] , [2] , [3] , [4] , [5]])
print(b)
print(b.shape)
print(b[4][0])
c = np.array([[1,2,3] , [4 ,5 ,6]])
print(c)
print(c.shape)
print(c[1][1])
print(" to create zeroes " )
a = np.zeros((3,3))

print(a)
print(" to create no of ones  ")
b = np.ones((2,3))
print(b)
print(" to create some constant ") 
c = np.full((3,2) , 5)
print(c)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
5
[[1 2 3]
 [4 5 6]]
(2, 3)
5
 to create zeroes 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 to create no of ones  
[[1. 1. 1.]
 [1. 1. 1.]]
 to create some constant 
[[5 5]
 [5 5]
 [5 5]]


In [4]:
# identity matrix 

d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# Random matrix 

In [6]:
randomMatrix = np.random.random((2 , 3))
print(randomMatrix)

[[0.18705528 0.06079678 0.69505364]
 [0.1725809  0.18316566 0.91750404]]


In [7]:
## Set some roe=ws and column with any values 

In [8]:
z = np.zeros((3 , 3 ) , dtype =  int)
print(z)
z[1 , :] = 5 
z[: , -1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [9]:
# DataTypes
print(z.dtype)

int64


In [10]:
# Mathematical Operations
x = np.array([[1 ,2] , [3 , 4 ]])
y = np.array([[5,6] , [7,8]])

In [11]:
print(x + y )

[[ 6  8]
 [10 12]]


In [12]:
print(np.subtract(x , y))

[[-4 -4]
 [-4 -4]]


In [13]:
a = np.array([1 , 2 ,3 ,4])

In [14]:
b = a + 5

In [15]:
print(a)
print(b)

[1 2 3 4]
[6 7 8 9]


In [16]:
# Stacking of arrays  

In [17]:
a = np.stack((a,b) , axis  =0)

In [18]:
#B REshape 
print(a)

[[1 2 3 4]
 [6 7 8 9]]


In [19]:
a = a.reshape((4,2))

In [20]:
print(a)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [21]:
print(array1.shape)

(6,)


In [22]:
array2 = np.array([1,2,3,4,5,6])

In [23]:
array2 = array2 + 6 

In [24]:
print(array2)


[ 7  8  9 10 11 12]


In [25]:
array3 = np.arange(30).reshape((5,3,2))

In [26]:
print(array3)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


In [27]:
x = np.array([[1,2] , [3 , 4]])
y = np.array([[5,6] , [7 , 8]])

In [28]:
print(x, y )
print(np.dot(x,y))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [29]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


## NUMPY RANDOM MODULE GENERATER

In [30]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
np.random.shuffle(a)

In [32]:
print(a)

[1 8 6 3 5 2 4 0 7 9]


In [33]:
# returns values from a. standard Normal Distributions 
a = np.random.rand(2 , 3)
print(a)
a = np.random.randint(5,10 ,3)
print(a)


[[0.05360526 0.74301131 0.80404034]
 [0.31142881 0.40793157 0.07393574]]
[6 5 6]


In [34]:
# Randomly pick one element from an array
element = np.random.choice([1,2,3,2,11,27])
print(element)

2


## Some more numpy Statistics function¶
- min max 
- mean 
- median
- average
- standard deviation 


In [36]:
a = np.array([[1,2,3,4] , [7,6,0,2]])
print(a)
print(np.min(a))
# Along with axis = 0 column wise axis = 1  row wise 
print(np.min(a , axis = 0 ))

[[1 2 3 4]
 [7 6 0 2]]
0
[1 2 0 2]


In [42]:
# mean and average of alla element 
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(np.mean(b))

3.0


In [33]:
np.random.seed(1)
a = np.random.rand(2 , 3)

In [26]:
print(a)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [27]:
a = np.random.randint(5 , 10 ,5 )

In [28]:
print(a)


[9 9 6 7 9]


In [29]:
element = np.random.choice(a)

In [30]:
print(element)

6


## Some more numpy Statistics function

In [32]:
a = np.array([[1 , 2,3 ,4] , [4 , 5, 6, 7]])

In [33]:
print(a)
print(np.min(a))
print(np.min(a , axis =1))

[[1 2 3 4]
 [4 5 6 7]]
1
[1 4]


In [34]:
b = np.array([1 , 2, 3,4])

In [35]:
np.mean(b)

2.5

In [36]:
np.mean(a)


4.0

In [37]:
np.mean(a , axis= 1)

array([2.5, 5.5])

In [38]:
c = np.array([1 , 5 ,4 ,2 ,0])

In [39]:
np.median(c)

2.0

In [40]:
w = np.array([1 , 2,3,4 ,5])

In [41]:
np.average(c , weights = w)

2.066666666666667

In [42]:
np.std(c)

1.854723699099141

In [43]:
np.var(c)

3.4400000000000004

## Scaler and vector 

- Scaler mean A value 
- Vector mean list of array 

In [44]:
x1 = np.array([ 4 ,5, 6])

In [46]:
print(x1)
x1.shape

[4 5 6]


(3,)

In [47]:
x2 = np.array([ [4] ,[5], [6]])

In [49]:
print(x2)
x2.shape

[[4]
 [5]
 [6]]


(3, 1)

### Norm of Vectors 

In [50]:
x = np.array([-15 , 3 ,10 ])

In [51]:
lp2 = np.linalg.norm(x)

In [52]:
print(lp2)

18.275666882497067


In [53]:
lp2 = np.linalg.norm(x , ord=1)
lpinf = np.linalg.norm(x , ord=np.inf)

In [54]:
print(lp2)
print(lpinf)

28.0
15.0


### Broadcasting


In [55]:
 l = [1 , 2,3 ,4]
l = np.array(l)


In [57]:
l=l+1
print(l)

[2 3 4 5]
