# lecture 4 

In [1]:
import numpy as np

In [2]:
f = np.arange(20).reshape(5,4)

In [3]:
f


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
f.sum()

190

In [5]:
f.sum(axis =1)

array([ 6, 22, 38, 54, 70])

In [6]:
f.sum(axis =0)

array([40, 45, 50, 55])

In [7]:
np.sum(f, axis = 0)

array([40, 45, 50, 55])

In [8]:
norm = np.random.randn(500 , 400)

In [9]:
norm.mean()

-0.0011690164010311058

In [10]:
np.std(norm)

0.9993857800332303

In [11]:
np.random.rand(5,5)

array([[0.86614376, 0.88970231, 0.08220962, 0.98774435, 0.96962416],
       [0.98694261, 0.30837251, 0.6804619 , 0.90750336, 0.09387433],
       [0.13271849, 0.10323724, 0.47416362, 0.30096286, 0.91805358],
       [0.68545755, 0.67582929, 0.68285371, 0.71951212, 0.47694068],
       [0.4230208 , 0.06672541, 0.2409644 , 0.76971003, 0.85970324]])

In [12]:
(np.random.rand(5,5)*100).astype(int)

array([[51, 36, 78, 53, 95],
       [89, 38, 80, 11, 72],
       [37, 24, 97, 56,  7],
       [38, 59, 23, 73,  6],
       [14, 89, 74,  2, 27]])

In [13]:
np.random.randint(0,100,(5,5))

array([[24, 71, 25, 90, 44],
       [41,  3,  2, 54, 23],
       [21, 83, 66, 89, 30],
       [50, 26, 57,  5, 10],
       [73, 41, 29, 62, 85]])

In [14]:
np.random.seed(6)

In [15]:
np.random.randint(0,100,size=(5,5))

array([[10, 73, 99, 84, 79],
       [80, 62, 25,  1, 75],
       [77, 57, 26, 33, 68],
       [33,  8,  2, 76, 84],
       [91, 31, 66,  5, 26]])

In [16]:
np.power(f , 2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [17]:
np.sum(f,axis = 0 , keepdims=True)


array([[40, 45, 50, 55]])

In [18]:
np.sum(f,axis = 1 , keepdims=True)

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [19]:
f


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
s = np.arange(8).reshape(4,2)

In [21]:
s


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
np.dot(f,s)

array([[ 28,  34],
       [ 76,  98],
       [124, 162],
       [172, 226],
       [220, 290]])

In [23]:
t = np.arange(20).reshape(5,4)

In [24]:
np.hstack([f,t])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])

In [25]:
np.vstack([f,t])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
np.concatenate([f,t] , axis= 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])