# Introduction to numpy 


In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6])

In [3]:
print(array1)

[1 2 3 4 5 6]


In [4]:
print(array1.shape)

(6,)


In [5]:
array2 = np.array([1,2,3,4,5,6])

In [6]:
array2 = array2 + 6 

In [7]:
print(array2)


[ 7  8  9 10 11 12]


In [8]:
array3 = np.arange(30).reshape((5,3,2))

In [9]:
print(array3)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]


In [10]:
x = np.array([[1,2] , [3 , 4]])
y = np.array([[5,6] , [7 , 8]])

In [11]:
print(x, y )
print(np.dot(x,y))

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [12]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


## NUMPY RANDOM MODULE GENERATER

In [25]:
np.random.seed(1)
a = np.random.rand(2 , 3)

In [26]:
print(a)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [27]:
a = np.random.randint(5 , 10 ,5 )

In [28]:
print(a)


[9 9 6 7 9]


In [29]:
element = np.random.choice(a)

In [30]:
print(element)

6


## Some more numpy Statistics function

In [32]:
a = np.array([[1 , 2,3 ,4] , [4 , 5, 6, 7]])

In [33]:
print(a)
print(np.min(a))
print(np.min(a , axis =1))

[[1 2 3 4]
 [4 5 6 7]]
1
[1 4]


In [34]:
b = np.array([1 , 2, 3,4])

In [35]:
np.mean(b)

2.5

In [36]:
np.mean(a)


4.0

In [37]:
np.mean(a , axis= 1)

array([2.5, 5.5])

In [38]:
c = np.array([1 , 5 ,4 ,2 ,0])

In [39]:
np.median(c)

2.0

In [40]:
w = np.array([1 , 2,3,4 ,5])

In [41]:
np.average(c , weights = w)

2.066666666666667

In [42]:
np.std(c)

1.854723699099141

In [43]:
np.var(c)

3.4400000000000004

## Scaler and vector 

- Scaler mean A value 
- Vector mean list of array 

In [44]:
x1 = np.array([ 4 ,5, 6])

In [46]:
print(x1)
x1.shape

[4 5 6]


(3,)

In [47]:
x2 = np.array([ [4] ,[5], [6]])

In [49]:
print(x2)
x2.shape

[[4]
 [5]
 [6]]


(3, 1)

### Norm of Vectors 

In [50]:
x = np.array([-15 , 3 ,10 ])

In [51]:
lp2 = np.linalg.norm(x)

In [52]:
print(lp2)

18.275666882497067


In [53]:
lp2 = np.linalg.norm(x , ord=1)
lpinf = np.linalg.norm(x , ord=np.inf)

In [54]:
print(lp2)
print(lpinf)

28.0
15.0


### Broadcasting


In [55]:
 l = [1 , 2,3 ,4]
l = np.array(l)


In [57]:
l=l+1
print(l)

[2 3 4 5]
